from sqlalchemy import Column,DateTime,Integer,Float, String
from datetime import datetime
from .database import Base

class PredictionLog(Base):
    __tablename__ = 'prediction_logs'
    
    id          = Column(Integer, primary_key=True, index=True)
    timestamp   = Column(DateTime, default=datetime.utcnow)
    prediction  = Column(Integer)
    probability = Column(Float)
    SeniorCitizen = Column(Float)
    tenure = Column(Float)
    MonthlyCharges = Column(Float)
    TotalCharges = Column(Float)
    gender_Female = Column(Float)
    gender_Male = Column(Float)
    Partner_No = Column(Float)
    Partner_Yes = Column(Float)
    Dependents_No = Column(Float)
    Dependents_Yes = Column(Float)
    PhoneService_No = Column(Float)
    PhoneService_Yes = Column(Float)
    MultipleLines_No = Column(Float)
    MultipleLines_No_phone_service = Column(Float)
    MultipleLines_Yes = Column(Float)
    InternetService_DSL = Column(Float)
    InternetService_Fiber_optic = Column(Float)
    InternetService_No = Column(Float)
    OnlineSecurity_No = Column(Float)
    OnlineSecurity_No_internet_service = Column(Float)
    OnlineSecurity_Yes = Column(Float)
    OnlineBackup_No = Column(Float)
    OnlineBackup_No_internet_service = Column(Float)
    OnlineBackup_Yes = Column(Float)
    DeviceProtection_No = Column(Float)
    DeviceProtection_No_internet_service = Column(Float)
    DeviceProtection_Yes = Column(Float)
    TechSupport_No = Column(Float)
    TechSupport_No_internet_service = Column(Float)
    TechSupport_Yes = Column(Float)
    StreamingTV_No = Column(Float)
    StreamingTV_No_internet_service = Column(Float)
    StreamingTV_Yes = Column(Float)
    StreamingMovies_No = Column(Float)
    StreamingMovies_No_internet_service = Column(Float)
    StreamingMovies_Yes = Column(Float)
    Contract_Month_to_month = Column(Float)
    Contract_One_year = Column(Float)
    Contract_Two_year = Column(Float)
    PaperlessBilling_No = Column(Float)
    PaperlessBilling_Yes = Column(Float)
    PaymentMethod_Bank_transfer_automatic = Column(Float)
    PaymentMethod_Credit_card_automatic = Column(Float)
    PaymentMethod_Electronic_check = Column(Float)
    PaymentMethod_Mailed_check = Column(Float)

class DriftAlert(Base):
    __tablename__="drift_alerts"

    id          = Column(Integer, primary_key=True, index=True)
    timestamp   = Column(DateTime, default=datetime.utcnow)
    feature_name= Column(String)
    ks_stat     = Column(Float)
    p_value     = Column(Float)
    severity    = Column(String)
    notified_at = Column(DateTime,nullable=True)
